language: node_js

node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - npm start -- --silent &

script:
  - npm run cypress:run --group foo --ci-build-id foo123
  - npm run cypress:run --group bar --ci-build-id foo123
  - npm run cypress:run --group baz --ci-build-id foo123
