language: node_js

node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - npm start -- --silent &

jobs:
  include:
    - stage: test
      script:
        - npm run cypress:run -- --record --group foo --ci-build-id foo123
    - stage: test
      script:
        - npm run cypress:run -- --record --group bar --ci-build-id foo123
    - stage: test
      script:
        - npm run cypress:run -- --record --group baz --ci-build-id foo123

